- .travis.yml
- README.rst
- setup.py
Final adjustements to this  repository in order to release `omero-metadata` 0.2.0 to PyPI.
The main adjustements are related to the renaming of this repository from `omero-cli-metadata` to `omero-metadata` and the corresponding adjustments in `omero-test-infra`
> 0.2.0 final fixes

- CHANGES.rst
- README.rst
- setup.py
- Add minimal CHANGES.rst  describing the relationship of omero-metadata:0.2.0 compared to OMERO 5.4.7
- Add warning about the usage of `OMERO_DEV_PLUGINS` when using the CLI metadata plugin
- Bump the version to 0.2.0
The filter branch statement can be verified by downloading the source of OMERO 5.4.7 and diffing the relevant files:
```
sbesson@lifesci-82385:omero-metadata (master) $ diff src/omero_cli_metadata.py /tmp/openmicroscopy-5.4.7/components/tools/OmeroPy/src/omero/plugins/metadata.py 
23,24c23
< import populate_metadata
< from omero.util import populate_roi, pydict_text_io
---
> from omero.util import populate_metadata, populate_roi, pydict_text_io
628a628,636
> 
> try:
>     if "OMERO_DEV_PLUGINS" in os.environ:
>         register("metadata", MetadataControl, HELP)
> except …
```
> 0.2.0 release

- CHANGES.rst
- src/omero_cli_metadata.py
- src/populate_metadata.py
- test/integration/metadata/test_populate.py
- test/integration/tablestest/test_populate_metadata.py
Added changes to support bulk annotations for projects and datasets, and to change csv reading to process the data line by line instead of buffering the data in memory and writing to the table all at once.
> Bulk annotations and streaming

- src/omero_cli_metadata.py
- src/populate_metadata.py
- test/integration/metadata/test_populate.py
As a preamble of upcoming work on the performance of the map annotation delete command, this PR:
- unifies the constructor of all the `Context` classes to support a `dry_run` boolean keyword, set to `False` by default
- updates the `DeleteMapAnnotationContext` OMERO deletion method to consume the `dry_run` argument
- updates the CLI `metadata populate` command to propagate the `dry-run` argument to the context class
This should allow to use `bin/omero metadata populate --context deletemap --dry-run` to measure a baseline and compare performance metrics for variations of the deletion commands without deleting the actual annotations on the server.
17e3737 updates the integration tests for the map deletion context class to test `ctx.parse()` with and without `--dry-run`
> Implement dry-run option in delete map context class

- src/populate_metadata.py
- test/integration/metadata/test_populate.py
Fixes #9 - see also discussion at https://github.com/openmicroscopy/openmicroscopy/pull/5832
This PR addresses a discrepancy in the naming of the image ID column for Project/Dataset hierarchies:
- when a bulk annotation is created from a CSV file where images are specified via ID via an `Image` column, an `Image` column is created in the OMERO.table
- when a bulk annotation is created from a CSV file where images are specified via name via an `Image Name` column, an `image` column is created in the OMERO.table
To reduce the cost on clients to support both forms, this PR proposes to unify the column name and use `Image` in agreement with the naming of other columns like `Well`, `Plate`.
ae81898 fixes the tests to use the local classes rather than the upstream deprecated `omero.util` …
> Image column name

- CHANGES.rst
- setup.py
This PR proposes to release the 2 PRs currently merged in https://github.com/ome/omero-metadata/milestone/2?closed=1 and deploy it as a PyPI pre-release.
This is largely motivated by the fact working with map annotation deletion in the context of IDR now requires some of the changes included in #11 (to ignore `Annotation` during the deletion operation for primary keys)
Alternatively, a `0.3.0` release could be cut today and all future API breaking improvements moved to `0.4.0`.
/cc @dominikl @joshmoore @jburel @kkoz @emilroz
> 0.3.0a1 pre-release of omero-metadata

- test/integration/clitest/test_metadata.py
Adjusts integration test to no longer expect `OriginalMetadataRequest` to return `header: GlobalMetadata` since https://github.com/openmicroscopy/bioformats/pull/3332. Corresponds with https://github.com/openmicroscopy/openmicroscopy/pull/6015.
> Adjust integration test for change in global metadata.

- src/populate_metadata.py
To prevent leaks in the server, table.close() has been made
more strict in:
* https://github.com/openmicroscopy/openmicroscopy/pull/6066
* https://github.com/ome/omero-blitz/pull/57
Calling getOriginalFile() after close() is now disallowed. This
PR slightly changes the semantics of `populate_from_reader` to
no longer call table close. Subclasses which override the method
shouldn't need modification if they use super(). Other invokers
of the method might need an additional close(), though the service
will be cleaned up on exit. Neither of these cases seems overly
burdensome.
cc: @chris-allan @emilroz @manics @pwalczysko @will-moore @mtbc
> Delay closing tables (API semantic change)

- README.rst
Added usage instructions to the README, particularly for ```populate``` command.
See it staged at https://github.com/will-moore/omero-metadata/tree/usage_instructions_in_README
> Usage instructions in readme

- src/omero_metadata/populate.py
This PR attempts to reduce the verbosity of the `populate` command when annotating a project or a dataset with a CSV file.
To test it, set up a dataset with a few images a CSV file as described in https://github.com/ome/omero-metadata#populate and run the populate command:
```
omero metadata populate --file=test.csv Project:<id>
```
Without this PR the command should log  info-level statements about missing plate and well columns. With this PR included, these irrelevant statements should be gone.
> Do not warn on missing well/plate names when the target is non HCS

- setup.py
`python setup.py test ... -k <string-to-match>` should work
> Add missing -k test-string to pytest

- README.rst
In testing https://github.com/ome/omero-metadata/pull/34#issuecomment-531734411
I found that the ```--fileid``` argument is not supported via the metadata CLI.
This removes it from the README, until it's fixed.
Also add dev install instructions, needed when developing or testing etc.
> readme dev install

- setup.py
The issue was encountered while working on the annotation of IDR dataset using a local Python 3 virtual environment. The `jinja2` requirement is mandatory for the context transforming bulk annotations into map annotations.
Note depending on the decisions on https://github.com/ome/omero-py/pull/114, this change might evolve into declaring a dependency on `omero-py` with some extra packages.
> Define jinja2 as a requirement of omero-metadata

- src/omero_metadata/populate.py
- test/integration/metadata/test_populate.py
This is primarily driven by the `idr0067` IDR submission as the [annotation file](https://github.com/IDR/idr0067-king-yeastmeiosis/blob/master/experimentA/idr0067-experimentA-annotation.csv contained Unicode characters for the genetic background. This PR generally improves support and test coverage for the creation of OMERO.tables from UTF-8 CSV files containing Unicode characters with and without BOM.
c2fb0f1 ensure the string is encoded to `utf-8` before calculating the maximum length of the string column
667ba18 enforces that CSV files are always opened with UTF-8 encoding and also uses context manager to close both file handles
44f69e9 also includes support for CSV files with a leading BOM character (Fixes #39)
The Unicode support was manually tested in an IDR annotation workflow from …
> Improved support for annotations with Unicode characters

- src/omero_metadata/cli.py
The behavior of the following subcommands is left unchanged:
- `rois`: pass the option to the graph command
- `bulkanns`, `measures`, `mapanns`, `allanns`: provide  additional information about the object
For the `populate` and `populateroi` command, `--report` was used as a way to increase the logging verbosity. This is now superseded by the more standard `-v/-q` which can be passed multiple times to control the logging verbosity e.g `omero metadata populate -qq`
The behavior of `omero metadata populate --report` is unchanged and equivalent to `omero metadata populate -v` but the option is removed from the usage in `omero metadata populate -h`
/cc @pwalczysko
> Fix usage --report option in the omero-metadata CLI plugin

- README.rst
- src/omero_metadata/populate.py
Adds an ImageWrapper to populate an OMERO.table at the image-level with ROI-level data. This requires an `roi` column containing ROI ID. Multiple rows per-ROI ID are allowed (see object-level case below), but ROIs with appropriate IDs must exist in image.
Note that the Tables dropdown is not populated at the image-level, but a `bulk annotations` file is added to attachments.
This can also be used to populate object-level analytics to refer to objects in a label image/mask associated with an ROI, where objects are encoded by their pixel value in the label image. There is currently no checking of this `object` column (for example, to confirm that these objects exist in the label image associated with the corresponding ROI), and this column need not exist at all. Once the label mask workflow …
> populate metadata at image-level

- src/omero_metadata/cli.py
- test/integration/clitest/test_metadata.py
New command to delete bulk annotation tables.
```
$ omero metadata deletebulkanns Project:1352 -n 
Using session for ...
FileAnnotation:27481235
$ omero metadata deletebulkanns Project:1352 
Using session for ...
FileAnnotation:27481235
$ omero metadata deletebulkanns Project:1352
Using session for ...
```
> Add deletebulkanns

- src/omero_metadata/populate.py
If an error is thrown during submit() and closehandle is true,
then the callback is automatically closed. If not, then the
caller is required to call `cb.close(True)` which will remove
the callback servant. If this is *not* done, then the following
type of error will be thrown on map annotation deletion:
```
serverExceptionClass = "ome.conditions.OverUsageException"
message = "servantsPerSession reached for 36cb8357-997a-46ff-b421-5b08d97cd3fc: 10000"
````
> Close callbacks

- README.rst
- src/omero_metadata/cli.py
- src/omero_metadata/populate.py
- test/integration/metadata/test_populate.py
When using `omero metadata populate --file data.csv` and the csv file specifies a `FloatColumn` should be used, empty cells cause a failure, even though there may be a valid use-case for missing values.
This PR allows missing values (empty string) by using a NaN value in the table.
When viewed in /webclient/omero_table/FILE_ID/ this is rendered as `nan` and is filtered out by any numerical queries, e.g.
`/webclient/omero_table/FILE_ID/?query=col_name>100` or `/webclient/omero_table/FILE_ID/?query=col_name<0`
See: https://idr-redmine.openmicroscopy.org/issues/201#note-25
Also updated README to fix `--file` (needed when passing csv to populate metadata) and to add a note about `roi.Name` needed when adding bulk annotations to Image: `omero metadata populate Image:123 --file data.csv`
> Nan values for bulk annotation tables

- README.rst
- src/omero_metadata/populate.py
In the case when we `populate metadata` on a target Image with a csv as in the README (below), the ROI IDs are already in the csv and we don't need the ROI.name in OMERO to identify which row applies to which ROI.
However, without this PR, any ROIs without the `name` set in OMERO would cause `populate metadata` to fail.
```
Roi,Shape,probability,area
501,1,0.8,250
502,1,0.9,500
503,1,0.2,25
```
To test:
- Draw some Shapes on an Image in iviewer and Save
- Note the ROI IDs from iviewer and update the ROIs in a csv like the one above.
- Run `populate metadata` script on the Image in webclient with the csv (this requires https://github.com/ome/omero-scripts/pull/184) or use the CLI.
- Should get an OMERO.table created on the Image with a `Roi Name` column where all the values will be empty
- …
> Roi name allowed none

- README.rst
- src/omero_metadata/populate.py
- test/integration/metadata/test_populate.py
This uses the name "Roi" for the `RoiColumn`, using the same convention we have adopted of "Image" for the `ImageColumn`.
I noticed @sbesson had 'Roi' column on his screenshot at https://github.com/ome/omero-web/pull/264#issuecomment-786023860
I was looking at loading a row for a particular ROI using:
```
/webgateway/table/Image/2567/query/?query=Roi-225611
```
To test:
- See image with ROIs at https://merge-ci.openmicroscopy.org/web/webclient/?show=image-39715
- Download the CSV attached - confirm it looks like this (NB: 1st column Name is `roi`).
```
roi,ROI_Area,Channel_Index,Channel_Name
418817,0.0469,1,DAPI
418818,0.142,2,GFP
418819,0.093,3,TRITC
418820,0.093,3,ACA
418821,0.093,3,foo
```
- Run the `Populate_Metadata.py` script on this image (can use the webclient UI and this also …
> Use 'Roi' for name of RoiColumn

- src/omero_metadata/populate.py
The problem appears when I ran 
```
omero metadata populate --context bulkmap --batch 100 --cfg idr0113-experimentA-bulkmap-config.yml Project:1855
```
the change was tested in the context above
```
omero metadata populate --context bulkmap --batch 100 --cfg idr0113-experimentA-bulkmap-config.yml Project:1855
Using session for demo@localhost:4064. Idle timeout: 10 min. Current group: Public
_save_annotation_and_links with batch size 100
INFO:omero_metadata.populate:Created/linked 110 MapAnnotations (total 110)
INFO:omero_metadata.populate:Created/linked 100 MapAnnotations (total 210)
INFO:omero_metadata.populate:Created/linked 10 MapAnnotations (total 220)
```
cc @sbesson
> add allow_nan flag to context

- src/omero_metadata/populate.py
- test/integration/metadata/test_populate.py
See https://github.com/IDR/idr0079-hartmann-lateralline/pull/5#issuecomment-901249131
Usage:
```
ctx = ParsingContext(
client, image._obj, file=csv_name, allow_nan=True,
table_name=table_name
)
ctx.parse()
```
This change used in https://github.com/IDR/idr0079-hartmann-lateralline/pull/5/commits/57e507fe24f34170d5b60a91e709ff6218bfbabd
to create bulk annotations with custom names:
NB: `ParsingContext()` has several parameters that are not used: `fileid`, `cfg`, `cfgid`, `attach`, `options`, `batch_size`, `loops`, `ms`. Seems like these should be removed, although that will break code that still includes them.
> Add table_name option to ParsingContext()

- setup.py
- src/omero_metadata/cli.py
- src/omero_metadata/populate.py
- This PR adds support to `DatasetColumn`, specifically support to a Dataset ID column
- This PR adds an option CLI `--detect_header` parameter to `omero metatdata populate` that automatically detects `column_type`. This aims to reduce the workload and remove the need for users to predefine the header types through automation.
Dataset ID column was necessary so that the `--detect_header` is easier and better implemented.
Tests passed locally with no failures.
Edit: Changed the default behavior to use the detect header method unless the user supplies a CSV with a custom header with `# header` or the new `--manual_header` flag. 
To do:
> Add --detect_header and DatasetColumn support

- src/omero_metadata/populate.py
Simply skip empty lines instead of crashing. Ran into this issue as well. Initially thought it's a linebreak at the end of the last entry, but that works fine actually. In order to replicate the issue you really need an empty line with a linebreak at the end of the file. As a side effect with the PR you can also have empty lines somewhere inbetween, they too will just be ignored.
Fixes https://github.com/ome/omero-metadata/issues/21 .
> Skip empty rows

- test/unit/test_automatic_header.py
While testing the README changes in https://github.com/ome/omero-metadata/pull/71, written some tests to assert the resolved column types from `omero metadata populate`. 
These tests provide insight and could help us align the expected behavior versus the executed behavior.
> Added column type tests

- README.rst
- src/omero_metadata/cli.py
- test/integration/metadata/test_populate.py
- test/unit/test_automatic_header.py
Fixes #76 
First create a minimal dataset/image hierarchy e.g. as follows:
```bash
touch test1.fake test2.fake
dataset=$(omero obj new Dataset name=sparse_table)
omero import -T $dataset test1.fake test2.fake
```
CSV files with sparse string data such as the one below are correctly handled by the current HEAD of `omero-metadata`.
```
$ cat sparse_string_column.csv 
Image name,meas1,meas2,meas3,meas4
test1.fake,1.1,1,high,low
test2.fake,0.5,2,,low
```
The columns with missing values are mapped as `s/StringCOlumn` and the missing value are turned into empty strings where running `omero metadata populate --file sparse_string_column.csv $dataset` e.g.
CSV files with sparse numerical columns such as the one below currently fail during the population command:
```csv
$ cat …
```
> Fix header detection for tables with sparse numerical data

- src/omero_metadata/populate.py
This particular line is creating as many entries in the log file as there is rows in the table! This is particularly bad in the case where number of rows in the tables reach >100k.
If there's no particular reason to keep it at the info level it would be great to change it to debug.
> "Nothing to do during post processing." from info to debug

- CHANGELOG.md
- src/omero_metadata/cli.py
This PR attempts to fix a regression introduced as part of https://github.com/ome/omero-metadata/pull/67 which was primarily tested with the `omero metadata populate` command
To reproduce, run a workflow composed of a table population followed by a bulk annotation -> map annotation population, for instance as described with https://omero-guides.readthedocs.io/en/latest/upload/docs/metadata.html.
With the current release of `omero-metadata 0.11.1`, the second step should fail with and error of type
```
$ omero metadata populate --context bulkmap --cfg simple-annotation-bulkmap-config.yml Dataset:601
Using session for import.user@localhost:4064. Idle timeout: 10 min. Current group: Demo Group
Traceback (most recent call last):
File "/opt/omero/OMERO.venv/bin/omero", line 8, in <module> …
```
> Only perform header detection when --file is specified

- src/omero_metadata/populate.py
- test/integration/metadata/test_populate.py
Comes from a discussion with @muhanadz. For scenarios where the `omero-metadata` plugin is used as a Python library, it is currently a requirement to make an additional query to retrieve the table created by `omero_metadata.populate.ParsingContext.parse()` operation.
As the implementation passes through the return value of `parse_from_handle_stream` https://github.com/ome/omero-metadata/blob/0ea482289812abf6adc58e13d2a49f71874d51d9/src/omero_metadata/populate.py#L1208-L1218, this PR amends the latter API to return the ID of the original file associated with the OMERO.table.
The unit tests are also amended to compare the output of the `parse()` API with the query and give an example of how a consumer might use the new functionality.
> Update ParsingContext.parse() to return the ID of the table

- src/omero_metadata/populate.py
- test/integration/clitest/test_metadata.py
See https://github.com/ome/omero-metadata/actions/runs/7490016877/job/20387910739
I assume the new operating system is pulling a more recent of `flake8` with additional warnings
> Fix flake8 issue raised following the Rocky Linux 9 image upgrade

- setup.py
- src/omero_metadata/cli.py
- src/omero_metadata/populate.py
- test/integration/clitest/test_metadata.py
- test/integration/metadata/test_populate.py
- test/integration/tablestest/test_populate_metadata.py
See https://github.com/ome/omero-metadata/pull/84#issuecomment-1888767870
Following the upgrade of the test infrastructure to Rocky Linux 9/Python 3.9 (see https://github.com/ome/omero-test-infra/pull/66), some of the tests started failing due to the presence of logging statements in the stdout conflicting with some of the `assert` checks.
After some investigation, this behavioral change does not look to be related to the operating system or Python version per se but is more specific to the testing infrastructure.
These changes depend on https://github.com/ome/omero-test-infra/pull/68 to call `pytest` directly instead of `python setup.py test` and revert a11343c71bf89d4d116137e1db96dff7e54e51ee.
> Integration tests: call pytest directly

- src/omero_metadata/cli.py
Allow to specify a custom table name for `metadata populate` command.
> Add tablename option
